### ISSUE TITLE
Все пропало, все пропало..

### ISSUE THREAD

**Issue by reskwer** [yoksel/pixel-glass-js#2]
Все пропало, все пропало.. IE11 не работает, точнее работает - но очень криво.
Пожалуйста хотя бы с 10 версии поддержку :)

**Comment by yoksel** [comment]
@reskwer постараюсь поправить, но быстро не обещаю

**Comment by yoksel** [comment]
@reskwer поправила, попробуйте обновиться. Инвертирование работать не будет, остальное должно быть в порядке

**Comment by reskwer** [comment]
Огромное спасибо, все работает :)
