### ISSUE TITLE
Пожелание.

### ISSUE THREAD

**Issue by reskwer** [yoksel/pixel-glass-js#3]
Юль, пожалуйста, сделай привязку состояния `on \ off`к кукам, плагин включил обновил html или js браузер перезагрузился и опять нужно включать((

У меня проекты по 25+ страниц, очень надоедает каждый рас включать заново ((

**Comment by VovanR** [comment]
@reskwer можно закомментировать эту строку https://github.com/yoksel/pixel-glass-js/blob/master/script.js#L106

**Comment by yoksel** [comment]
@VovanR разве что как временный костыль : ))
Я поправлю

**Comment by yoksel** [comment]
@reskwer Настройки сохранялись, но я это поломала когда чинила для IE : ( Тысяча извинений.

Попробуйте обновиться, должно всё работать.
