### ISSUE TITLE
импорт из папки node_modules

### ISSUE THREAD

**Issue by cactusjam** [yoksel/pixel-glass-js#4]
невозможно импортировать скрипт js из папки node_modules.
возможно проблема с правами доступа в папку.
работает если перенести файлы в любую другую папку.

**Comment by yoksel** [comment]
Используете ли локальный сервер? Из какой папки в этом случае показывается содержимое?

**Comment by cactusjam** [comment]
использую gulp. содержимое перенесено в папку ..\source\js

**Comment by yoksel** [comment]
Если сервер смотрит в source, ему может быть не видна папка node_modules,  в этом случае нужно скопировать файлы проекта в папку, в которую смотрит сервер, и подключать оттуда

**Comment by cactusjam** [comment]
вероятно так и есть. спасибо за оперативный ответ.
